### PR TITLE
Branding Synexis Guild

### PR DESCRIPTION
**Pull request by BuKiKoa**
add info.json 
add logo.png
add logo.svg

### CODE REVIEW

**Comment by BuKiKoa** [comment]
{
  "address": "erd1efe954adel2jchnl98xt2gnkrtz0gwpap5ap2mzwvuez0d5344qs2llhcv",
  "message": "0x34373962313164666534373364316266376166343063393030643863636661663333383433356337",
  "signature": "0x80b33067e8f7dab9c9971e6813a674aef259c9c3db2063ba2f2e6ebd98b82197e931f41692f6cfe38df00390c676f8f8d8f9685de45a93cc1eba218db701a109",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by bcosma** [comment]
@BuKiKoa can you add website in the JSON file?

**Comment by BuKiKoa** [comment]
@bcosma just added :   "website": null lmk if it's ok.

**Comment by bcosma** [comment]
@BuKiKoa can you set it as an empty string?

**Comment by BuKiKoa** [comment]
@bcosma Done

**Review by bcosma — APPROVED** [review]

**Pull request merged**
