### PR TITLE
Ninja Staking

### PR DESCRIPTION
**Pull request by CryptoFirefly**
Ninja Staking

{
  "address": "erd1lapzkgcmsvs7u43ga6rsc0jq4r0atefznt0m3patvtwwqz5u990syrmxty",
  "message": "0x30366431386466333865333363303361666236313166633833656234666533356637343636316332",
  "signature": "0x53f3e3481b3eb740469279409160e8b05a241e68ddd94ac50f0d6c0ad760dfb64e3bf88723669e0a60d14846ee60f031674e1dee8089605b03bdea5cef04630b",
  "version": 1,
  "signer": "ErdJS"
}

### CODE REVIEW

**Comment by CryptoFirefly** [comment]
Branding for Ninja Staking.

**Comment by bcosma** [comment]
@CryptoFirefly which commit hash did you use for signing? The signature cannot be validated against the latest commit hash (ab7720970285b38c9886cbfd3f2612b5a58c5065)

**Comment by CryptoFirefly** [comment]
> @CryptoFirefly which commit hash did you use for signing? The signature cannot be validated against the latest commit hash ([ab77209](https://github.com/utrustdev/xmoney-assets/commit/ab7720970285b38c9886cbfd3f2612b5a58c5065))

hi,

I used the hash from Commit #5 ... Could i get help on which Hash i should be using to generate the signature. I am new to GitHub and unable to identify which hash i should be using.

**Comment by CryptoFirefly** [comment]
> @CryptoFirefly which commit hash did you use for signing? The signature cannot be validated against the latest commit hash ([ab77209](https://github.com/utrustdev/xmoney-assets/commit/ab7720970285b38c9886cbfd3f2612b5a58c5065))

Does this look like the right Signature. Used Hash - ab7720970285b38c9886cbfd3f2612b5a58c5065

{
  "address": "erd1lapzkgcmsvs7u43ga6rsc0jq4r0atefznt0m3patvtwwqz5u990syrmxty",
  "message": "0x61623737323039373032383562333863393838366362666433663236313262356135386335303635",
  "signature": "0x5f50a5b9bcc624bd5ddbc022f4904792794a33f8707dbe18eabc071eacd21fa9c6d8da9c6b70b2c67e14b1f35a32b08ebfe66bc3c5da02c079bd52da212dc401",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by bcosma** [comment]
yes it is correct. Thank you

**Pull request merged**
