### PR TITLE
APAC Guilds

### PR DESCRIPTION
**Pull request by louishk**
Adding info JSON + logo png & svg for guild branding

### CODE REVIEW

**Comment by louishk** [comment]
{
  "message": "39373462623135626436343761623365353430376231393033303764316439336432663134313661",
  "signature": "ef8a953b11f40aaf9087fc464b8aebfe20500bf6f803ba58ee35af67f1289d9670b0cb621ebb52c505db2f352f45c4c9683722f19084c186ac72927c06225308",
  "address": "erd1ppexas6h8sy65mq3y3rnzfghwh6try30fvpkqc2j4x20v3r4p6psqel4ge",
  "version": 1,
  "signer": "wallet-connect-v2"
}

**Comment by bcosma** [comment]
@louishk can you add smaller size icons?

**Comment by louishk** [comment]
> @louishk can you add smaller size icons?

@bcosma can you advise the specs then ? i have uploaded what was asked .png & .svp 200x200 on the guild FAQ "_Add Your Guild Logo
In the newly created folder, add two logo files for your guild:
logo.png: A PNG version of your logo ( 200x200 pixels )
logo.svg: An SVG version of your logo ( 200x200 pixels )
Both files should ideally have a square aspect ratio for optimal display across the xMoney Guild platform."_

**Review by louishk — COMMENTED** [review]
compressed svg

**Comment by bcosma** [comment]
@louishk can you pull an update from master branch? I increased the min size to 200 kb

**Comment by louishk** [comment]
> @louishk can you pull an update from master branch? I increased the min size to 200 kb

@bcosma done

**Comment by bcosma** [comment]
@louishk please add a website address, or an empty string.

**Review by bcosma — APPROVED** [review]

**Pull request merged**
